Mongodb connection and folders
lordjnux/backend-hobbify pull request #2
Opened 2024-06-26 23:23 UTC by SebastianSilvaA

Agregue la conexion a la base de datos de mongoDB con sus respectivas variables de entorno, ademas cree el modulo y las carpetas necesarias para empezar a trabajar en la implementacion del guardado del chat en la base de datos

2024-06-26 23:36 UTC, lordjnux commented on api-rest/src/config/mongodb.config.ts
Agregar try-catch para el manejo del error por si ocurre algún error al intentar realizar la conexión

2024-06-27 00:03 UTC, lordjnux commented on api-rest/src/mongodb/models/chat.model.ts
Schema describe una movie, movieModel ?

2024-06-27 00:05 UTC, lordjnux requested changes
Realizar los cambios que te coloqué en los comentarios de cada archivo donde hay que hacerlos y listo, hacer PR de nuevo.
En general, muy buen trabajo!

2024-06-27 00:08 UTC, SebastianSilvaA commented on api-rest/src/mongodb/models/chat.model.ts
eso me olvide de borrarlo,

2024-06-27 00:15 UTC, closed without merging